"""create initial guild tables

Revision ID: 3fae0b4c646f
Revises: 
Create Date: 2026-08-11 15:28:40.195982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fae0b4c646f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('guilds',
    sa.Column('guild_id', sa.UUID(), nullable=False),
    sa.Column('guild_name', sa.String(length=100), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.user_id'], name=op.f('fk_guilds_owner_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('guild_id', name=op.f('pk_guilds'))
    )
    op.create_index(op.f('ix_guilds_owner_id'), 'guilds', ['owner_id'], unique=False)
    op.create_table('guild_memberships',
    sa.Column('guild_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'member', name='guild_role', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.guild_id'], name=op.f('fk_guild_memberships_guild_id_guilds'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_guild_memberships_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('guild_id', 'user_id', name=op.f('pk_guild_memberships'))
    )
    op.create_index(op.f('ix_guild_memberships_user_id'), 'guild_memberships', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_guild_memberships_user_id'), table_name='guild_memberships')
    op.drop_table('guild_memberships')
    op.drop_index(op.f('ix_guilds_owner_id'), table_name='guilds')
    op.drop_table('guilds')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
