"""create channels table

Revision ID: 56e1899223f9
Revises: 3fae0b4c646f
Create Date: 2026-08-27 20:21:24.043696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56e1899223f9'
down_revision: Union[str, Sequence[str], None] = '3fae0b4c646f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('guild_id', sa.UUID(), nullable=False),
    sa.Column('channel_name', sa.String(length=100), nullable=False),
    sa.Column('channel_type', sa.Enum('text', name='channel_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.guild_id'], name=op.f('fk_channels_guild_id_guilds'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('channel_id', name=op.f('pk_channels'))
    )
    op.create_index(op.f('ix_channels_guild_id'), 'channels', ['guild_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_channels_guild_id'), table_name='channels')
    op.drop_table('channels')
    # ### end Alembic commands ###
